// Generated by gencpp from file yhs_msgs/PathArray.msg
// DO NOT EDIT!


#ifndef YHS_MSGS_MESSAGE_PATHARRAY_H
#define YHS_MSGS_MESSAGE_PATHARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace yhs_msgs
{
template <class ContainerAllocator>
struct PathArray_
{
  typedef PathArray_<ContainerAllocator> Type;

  PathArray_()
    : paths()  {
    }
  PathArray_(const ContainerAllocator& _alloc)
    : paths(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::nav_msgs::Path_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nav_msgs::Path_<ContainerAllocator> >::other >  _paths_type;
  _paths_type paths;





  typedef boost::shared_ptr< ::yhs_msgs::PathArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_msgs::PathArray_<ContainerAllocator> const> ConstPtr;

}; // struct PathArray_

typedef ::yhs_msgs::PathArray_<std::allocator<void> > PathArray;

typedef boost::shared_ptr< ::yhs_msgs::PathArray > PathArrayPtr;
typedef boost::shared_ptr< ::yhs_msgs::PathArray const> PathArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_msgs::PathArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_msgs::PathArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yhs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'yhs_msgs': ['/home/xwqf/catkin_ws/src/yhs_bringup/yhs_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yhs_msgs::PathArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_msgs::PathArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_msgs::PathArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_msgs::PathArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_msgs::PathArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_msgs::PathArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_msgs::PathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ac7ec67d8c4222b3a71671051b1fa81";
  }

  static const char* value(const ::yhs_msgs::PathArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ac7ec67d8c4222bULL;
  static const uint64_t static_value2 = 0x3a71671051b1fa81ULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_msgs::PathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_msgs/PathArray";
  }

  static const char* value(const ::yhs_msgs::PathArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_msgs::PathArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
nav_msgs/Path[] paths\n\
\n\
================================================================================\n\
MSG: nav_msgs/Path\n\
#An array of poses that represents a Path for a robot to follow\n\
Header header\n\
geometry_msgs/PoseStamped[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::yhs_msgs::PathArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_msgs::PathArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_msgs::PathArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_msgs::PathArray_<ContainerAllocator>& v)
  {
    s << indent << "paths[]" << std::endl;
    for (size_t i = 0; i < v.paths.size(); ++i)
    {
      s << indent << "  paths[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "    ", v.paths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_MSGS_MESSAGE_PATHARRAY_H
