// Generated by gencpp from file yhs_msgs/PathIsValid.msg
// DO NOT EDIT!


#ifndef YHS_MSGS_MESSAGE_PATHISVALID_H
#define YHS_MSGS_MESSAGE_PATHISVALID_H

#include <ros/service_traits.h>


#include <move_base/PathIsValidRequest.h>
#include <move_base/PathIsValidResponse.h>


namespace yhs_msgs
{

struct PathIsValid
{

typedef PathIsValidRequest Request;
typedef PathIsValidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathIsValid
} // namespace yhs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yhs_msgs::PathIsValid > {
  static const char* value()
  {
    return "226709eb87617a56921e4d4580ddd926";
  }

  static const char* value(const ::yhs_msgs::PathIsValid&) { return value(); }
};

template<>
struct DataType< ::yhs_msgs::PathIsValid > {
  static const char* value()
  {
    return "yhs_msgs/PathIsValid";
  }

  static const char* value(const ::yhs_msgs::PathIsValid&) { return value(); }
};


// service_traits::MD5Sum< ::yhs_msgs::PathIsValidRequest> should match 
// service_traits::MD5Sum< ::yhs_msgs::PathIsValid > 
template<>
struct MD5Sum< ::yhs_msgs::PathIsValidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yhs_msgs::PathIsValid >::value();
  }
  static const char* value(const ::yhs_msgs::PathIsValidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yhs_msgs::PathIsValidRequest> should match 
// service_traits::DataType< ::yhs_msgs::PathIsValid > 
template<>
struct DataType< ::yhs_msgs::PathIsValidRequest>
{
  static const char* value()
  {
    return DataType< ::yhs_msgs::PathIsValid >::value();
  }
  static const char* value(const ::yhs_msgs::PathIsValidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yhs_msgs::PathIsValidResponse> should match 
// service_traits::MD5Sum< ::yhs_msgs::PathIsValid > 
template<>
struct MD5Sum< ::yhs_msgs::PathIsValidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yhs_msgs::PathIsValid >::value();
  }
  static const char* value(const ::yhs_msgs::PathIsValidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yhs_msgs::PathIsValidResponse> should match 
// service_traits::DataType< ::yhs_msgs::PathIsValid > 
template<>
struct DataType< ::yhs_msgs::PathIsValidResponse>
{
  static const char* value()
  {
    return DataType< ::yhs_msgs::PathIsValid >::value();
  }
  static const char* value(const ::yhs_msgs::PathIsValidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YHS_MSGS_MESSAGE_PATHISVALID_H
