// Generated by gencpp from file yhs_msgs/PathIsValidResponse.msg
// DO NOT EDIT!


#ifndef YHS_MSGS_MESSAGE_PATHISVALIDRESPONSE_H
#define YHS_MSGS_MESSAGE_PATHISVALIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yhs_msgs
{
template <class ContainerAllocator>
struct PathIsValidResponse_
{
  typedef PathIsValidResponse_<ContainerAllocator> Type;

  PathIsValidResponse_()
    : result(0)  {
    }
  PathIsValidResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathIsValidResponse_

typedef ::yhs_msgs::PathIsValidResponse_<std::allocator<void> > PathIsValidResponse;

typedef boost::shared_ptr< ::yhs_msgs::PathIsValidResponse > PathIsValidResponsePtr;
typedef boost::shared_ptr< ::yhs_msgs::PathIsValidResponse const> PathIsValidResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yhs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'yhs_msgs': ['/home/yhs/ME/src/yhs_bringup/yhs_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const ::yhs_msgs::PathIsValidResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_msgs/PathIsValidResponse";
  }

  static const char* value(const ::yhs_msgs::PathIsValidResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int8 result\n\
\n\
";
  }

  static const char* value(const ::yhs_msgs::PathIsValidResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathIsValidResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_msgs::PathIsValidResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_msgs::PathIsValidResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_MSGS_MESSAGE_PATHISVALIDRESPONSE_H
