// Generated by gencpp from file yhs_msgs/SetCostmaps.msg
// DO NOT EDIT!


#ifndef YHS_MSGS_MESSAGE_SETCOSTMAPS_H
#define YHS_MSGS_MESSAGE_SETCOSTMAPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>

namespace yhs_msgs
{
template <class ContainerAllocator>
struct SetCostmaps_
{
  typedef SetCostmaps_<ContainerAllocator> Type;

  SetCostmaps_()
    : virtual_poses()  {
    }
  SetCostmaps_(const ContainerAllocator& _alloc)
    : virtual_poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseArray_<ContainerAllocator> >::other >  _virtual_poses_type;
  _virtual_poses_type virtual_poses;





  typedef boost::shared_ptr< ::yhs_msgs::SetCostmaps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yhs_msgs::SetCostmaps_<ContainerAllocator> const> ConstPtr;

}; // struct SetCostmaps_

typedef ::yhs_msgs::SetCostmaps_<std::allocator<void> > SetCostmaps;

typedef boost::shared_ptr< ::yhs_msgs::SetCostmaps > SetCostmapsPtr;
typedef boost::shared_ptr< ::yhs_msgs::SetCostmaps const> SetCostmapsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yhs_msgs::SetCostmaps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yhs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'yhs_msgs': ['/home/yhs/ME/src/yhs_bringup/yhs_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yhs_msgs::SetCostmaps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yhs_msgs::SetCostmaps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yhs_msgs::SetCostmaps_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b31025ae812e99e680b966d376dc03ad";
  }

  static const char* value(const ::yhs_msgs::SetCostmaps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb31025ae812e99e6ULL;
  static const uint64_t static_value2 = 0x80b966d376dc03adULL;
};

template<class ContainerAllocator>
struct DataType< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yhs_msgs/SetCostmaps";
  }

  static const char* value(const ::yhs_msgs::SetCostmaps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/PoseArray[] virtual_poses\n\
\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::yhs_msgs::SetCostmaps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.virtual_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCostmaps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yhs_msgs::SetCostmaps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yhs_msgs::SetCostmaps_<ContainerAllocator>& v)
  {
    s << indent << "virtual_poses[]" << std::endl;
    for (size_t i = 0; i < v.virtual_poses.size(); ++i)
    {
      s << indent << "  virtual_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "    ", v.virtual_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YHS_MSGS_MESSAGE_SETCOSTMAPS_H
